name: Build
on:
  workflow_dispatch:
    inputs:
      otp-ref-name:
        required: true
      otp-ref:
        required: true
      openssl-version:
        default: "3.5.8"
      wxwidgets-version:
        default: "3.2.10"
      target:
        type: choice
        default: "all"
        options:
          - all
          - linux
          - macos
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu-ubuntu-22.04
          - aarch64-unknown-linux-gnu-ubuntu-22.04
          - x86_64-unknown-linux-gnu-ubuntu-24.04
          - aarch64-unknown-linux-gnu-ubuntu-24.04
          - x86_64-unknown-linux-gnu-ubuntu-26.04
          - aarch64-unknown-linux-gnu-ubuntu-26.04
jobs:
  build_macos:
    name: "Build ${{ inputs.otp-ref-name }}-${{ matrix.pair.target }} (${{ matrix.pair.os }})"
    runs-on: ${{ matrix.pair.os }}
    permissions:
      actions: write
      contents: write
      id-token: write
      attestations: write
    env:
      OPENSSL_VERSION: ${{ inputs.openssl-version }}
      OPENSSL_DIR: /tmp/openssl-${{ matrix.pair.target }}
      OTP_REF: ${{ inputs.otp-ref }}
      OTP_REF_NAME: ${{ inputs.otp-ref-name }}
      OTP_DIR: /tmp/otp-${{ matrix.pair.target }}
      OTP_TGZ: /tmp/otp.tar.gz
      TARGET: ${{ matrix.pair.target }}
      WXWIDGETS_VERSION: ${{ inputs.wxwidgets-version }}
      WXWIDGETS_DIR: /tmp/wxwidgets-${{ matrix.pair.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              os: macos-15-intel
              target: x86_64-apple-darwin
          - pair:
              os: macos-15
              target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Check skip
        run: |
          ./scripts/check_skip.bash "${{ inputs.target }}" "$TARGET" "$OTP_REF_NAME"

      - name: Update OPENSSL_VERSION
        if: ${{ contains(env.OTP_REF_NAME, 'OTP-25') || contains(env.OTP_REF_NAME, 'maint-25') }}
        run: echo "OPENSSL_VERSION=1.1.1w" >> "$GITHUB_ENV"

      - uses: actions/cache@v6.1.0
        if: ${{ env.SKIP != 'true' }}
        with:
          path: ${{ env.OPENSSL_DIR }}
          key: openssl-${{ env.OPENSSL_VERSION }}-${{ matrix.pair.os }}-${{ matrix.pair.target }}

      - uses: actions/cache@v6.1.0
        if: ${{ env.SKIP != 'true' }}
        with:
          path: ${{ env.WXWIDGETS_DIR }}
          key: wxwidgets-${{ env.WXWIDGETS_VERSION }}-${{ matrix.pair.os }}-${{ matrix.pair.target }}

      # # Uncomment when testing
      # - uses: actions/cache@v6.1.0
      #   id: otp-cache
      #   with:
      #     path: ${{ env.OTP_DIR }}
      #     key: "otp-${{ env.OTP_REF_NAME }}\
      #           -${{ env.OTP_REF }}\
      #           -openssl-${{ env.OPENSSL_VERSION }}\
      #           -wxwidgets-${{ env.WXWIDGETS_VERSION }}\
      #           -${{ matrix.pair.target }}"

      - name: "Build OTP"
        if: ${{ env.SKIP != 'true' }}
        run: |
          bash scripts/build_otp_macos.bash "${{ env.OTP_REF_NAME }}"

      - name: "Attest build provenance"
        if: ${{ env.SKIP != 'true' }}
        uses: actions/attest-build-provenance@v4.1.1
        id: attest-build-provenance
        with:
          subject-path: ${{ env.OTP_TGZ }}

      - name: "Upload"
        if: ${{ env.SKIP != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATTESTATION: ${{ steps.attest-build-provenance.outputs.bundle-path }}
          WXWIDGETS_VERSION: ${{ inputs.wxwidgets-version }}
        run: |
          ./scripts/upload.bash

  build_linux:
    name: "Build ${{ inputs.otp-ref-name }}-${{ matrix.target }}"
    runs-on: ${{ startsWith(matrix.target, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      actions: write
      contents: write
      id-token: write
      attestations: write
    env:
      OTP_REF: ${{ inputs.otp-ref }}
      OTP_REF_NAME: ${{ inputs.otp-ref-name }}
      OTP_TGZ: /tmp/otp.tar.gz
      TARGET: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu-ubuntu-22.04
          - aarch64-unknown-linux-gnu-ubuntu-22.04
          - x86_64-unknown-linux-gnu-ubuntu-24.04
          - aarch64-unknown-linux-gnu-ubuntu-24.04
          - x86_64-unknown-linux-gnu-ubuntu-26.04
          - aarch64-unknown-linux-gnu-ubuntu-26.04
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Check skip
        run: |
          ./scripts/check_skip.bash "${{ inputs.target }}" "$TARGET" "$OTP_REF_NAME"

      - name: "Build OTP"
        if: ${{ env.SKIP != 'true' }}
        run: |
          ./scripts/build_otp_linux.bash "$OTP_REF_NAME" "$TARGET"

      - name: "Attest build provenance"
        if: ${{ env.SKIP != 'true' }}
        uses: actions/attest-build-provenance@v4.1.1
        id: attest-build-provenance
        with:
          subject-path: ${{ env.OTP_TGZ }}

      - name: "Upload"
        if: ${{ env.SKIP != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATTESTATION: ${{ steps.attest-build-provenance.outputs.bundle-path }}
        run: |
          ./scripts/upload.bash
