name: Sync OTP versions
on:
  schedule:
    # Run at 00:00
    - cron: '0 0 * * *'
jobs:
  sync_otp_versions:
    name: "Sync OTP versions"
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: "Sync nightly"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for ref_name in master maint maint-{25,26,27}; do
            ref=$(gh api repos/erlang/otp/commits/"$ref_name" --jq .sha)
            gh workflow run build.yaml --field otp-ref-name="$ref_name" --field otp-ref="$ref"
          done
